### ISSUE TITLE
Multicast routing to Wireguard

### ISSUE THREAD

**Issue by rsaffi** [troglobit/mrouted#34]
Hello,

Is there a straightforward way to have `mrouted` route multicast traffic from my local network (on `eth0`) to my Wireguard interface (on `wg0`)?

I tried bringing it up without any configuration and I got:

```
# mrouted -n -l debug
mrouted: 17:16:35.996 mrouted version 4.0-rc1 starting
mrouted: 17:16:35.996 Getting vifs from kernel interfaces
mrouted: 17:16:35.997 Installing eth0 (10.1.1.2 on subnet 10.1.1/24) as VIF #0, rate 0 pps
mrouted: 17:16:35.997 Getting vifs from /etc/mrouted.conf
mrouted: 17:16:35.997 Cannot forward: only one enabled vif
```

But then how would I go about setting the Wireguard interface on /etc/mrouted.conf? I tried via `phyint wg0`, but it doesn't work.

Thanks in advance!

**Comment by troglobit** [comment]
Hi,

I'm taking my first stumbling steps with Wireguard myself, so it's nice to hear back from users trying it out with mrouted as well! :)

From what I gather you seem to be able to run Wireguard in many different setups.  My VPN provider give me a routed point-to-point L3 link.  The interface in Linux has the following flags: `POINTOPOINT,NOARP,UP,LOWER_UP`

From those flags I can tell you mrouted will automatically filter out the `wireguard` interface, because the `MULTICAST` flag is not set.   Also, for this to work, besides that missing flag, you'd need to have another mrouted instance running on the other side of the tunnel.  

For things to work, you have to set up tunnels between multicast capable islands.  In the early beginnings this was done with IP-IP tunnels, which mrouted has built-in support for (as long as you have the kernel module loaded), but today most people use GRE tunnels to connect routing domains.  I.e., you can run Wireguard in whatever mode you like, as long as you then have a GRE tunnel on top of that and use the `greN` interface in your mrouted .conf.  If you set up GRE, remember to check that the MULTICAST flag is set.

**Comment by troglobit** [comment]
Closing, no reply within a reasonable time frame.
