### ISSUE TITLE
mrouted 4.0 reports "warning - Cannot disable multicast routing in kernel: Permission denied" when starting

### ISSUE THREAD

**Issue by F-i-f** [troglobit/mrouted#35]
System:
mrouted 4.0
linux kernel 5.5.17
Fedora 31

Every time mrouted starts, it reports:
```
mrouted[242850]: warning - Cannot disable multicast routing in kernel: Permission denied
```

Otherwise it seems to be working properly.

**Comment by troglobit** [comment]
Weird, that warning comes from `k_stop_dvmrp()` which is only called on `SIGHUP` and when shutting down mrouted?  Is it possible that you're seeing mrouted restart or something like that?

Anyway, the root cause turned out to be in the `cleanup()` function which called `k_stop_dvmrp()` twice.  I'll post a fix in a minute to address this, which I believe fixes what you are seeing.

Thank you for taking the time to report this! <3

**Comment by F-i-f** [comment]
Confirmed that 50b24f7 takes care of the problem.

**Comment by troglobit** [comment]
Awesome, thank you for verifying!
