### ISSUE TITLE
no phyint config option does not work

### ISSUE THREAD

**Issue by Luth1ng** [troglobit/mrouted#36]
Hello there,

I am facing an issue while using the new "no phyint" option in /etc/mrouted.conf file.

I installed the 4.0 mrouted package through with OpenBSD 6.6 using:
```
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
make
make install-strip
```

I am using 100+ virtual interfaces (vlan/carp) on my system, and when I try to start mrouted with the "no phyint" option enabled and 3-4 interfaces enabled manually, I am still getting the following error:

```
warning - too many vifs, ignoring <if>
warning - /etc/mrouted.conf:29 phyint <if> not available, continuing . . . 
Cannot forward: only one enabled vif
```

(only one interface is enabled, because it's the first in the kernel list I guess).

**It seems the "no phyint" option has no effect.**
Any idea ?

Thanks
Luthing

**Comment by troglobit** [comment]
It works here, on Linux.

However, I noticed that it scans all legible kernel interfaces and says it to installs them.  Even though it, in a second pass, only activates the ones I've explicitly enabled.

```
mrouted: 19:07:54.890 Getting vifs from kernel interfaces
mrouted: 19:07:54.890 Installing wlan0 (192.168.1.195 on subnet 192.168.1/24) as VIF #0, rate 0 pps
mrouted: 19:07:54.890 Installing virbr0 (192.168.122.1 on subnet 192.168.122/24) as VIF #1, rate 0 pps
mrouted: 19:07:54.890 Installing wg0 (10.0.196.136 on subnet 10.0.196/24) as VIF #2, rate 0 pps
mrouted: 19:07:54.890 Getting vifs from test.conf
mrouted: 19:07:54.890 Installing vifs in mrouted ...
mrouted: 19:07:54.890 vif #1, phyint 192.168.122.1
mrouted: 19:07:54.890 vif #2, phyint 10.0.196.136
```

Looking closer at the code this is indeed the bug you've hit.  Sorry about that.  Unfortunately I cannot give you an estimate for a fix, but I'll see what I can do over the weekend.  Should be fairly straight-forward since I know there's working code in the pimd project we can backport to mrouted.  (pimd was derived from mrouted back in the day and shares a lot of the same code.)

**Comment by troglobit** [comment]
@Luth1ng There, took quite a bit longer than I'd initially hoped. Had to refactor the entire interface probing/install, so the chance of regressions is quite high. I'd really appreciate if you could help verify the latest master, or something newer than 22068c0.

**Comment by troglobit** [comment]
Released in https://github.com/troglobit/mrouted/releases/tag/4.1
